# Generated by Django 6.0.6 on 2026-06-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gender',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
