# Generated by Django 6.0.6 on 2026-06-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (Compra/Reabastecimiento)'), ('OUT', 'Salida (Venta)'), ('ADJUSTMENT', 'Ajuste Manual')], max_length=15)),
                ('quantity', models.IntegerField(help_text='Cantidad del movimiento (usar valores positivos)')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
