# Generated by Django 6.0.6 on 2026-06-27 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(upload_to='comprobantes/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Verificación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
